homepage:
  number_of_episodes: 5

newsletter:
  from: ben@theorbitalmechanics.com
  default_send_time: 12:00:00 -08:00

markup:
  header_symbol: '#' # Set a symbol to indicate a line is a header not included in the list below. Use for uncommon headers.
  # A list of common headers. Use 'shorthand':'output' to allow us to recognize shorthand or old forms. Just list an output if you don't need to handle alternatives.
  # This markup is CaSe AgNoStIc, so don't worry about including capitalization variations.
  # Use three asterisks as a wildcard, rendered as part of the title. Headers get specific formatting, so we don't recognize bold or italic or links in those sections.
  headers: {'Spaceflight News',
            'Short & Sweet',
            'Questions, Comments and Correction Burns',
            'Questions, Comments, Corrections':'Questions, Comments and Correction Burns',
            'Interview -- ***',
            'This Week in Spaceflight History',
            'This week in SF history':'This Week in Spaceflight History',
            'Data Relay -- ***'}

# Definitions from https://help.apple.com/itc/podcasts_connect/#/itcb54353390
rss:
  title: 'The Orbital Mechanics Podcast'
# The show title.
# It’s important to have a clear, concise name for your podcast. Make your title specific. A show titled Our Community Bulletin is too vague to attract many subscribers,
# no matter how compelling the content.
# Pay close attention to the title as Apple Podcasts uses this field for search.
# If you include a long list of keywords in an attempt to game podcast search, your show may be removed from the Apple directory.

  language: 'en-US'
# The language spoken on the show.
# Because Apple Podcasts is available in territories around the world, it is critical to specify the language of a podcast. Apple Podcasts only supports values from the
# ISO 639 list (two-letter language codes, with some possible modifiers, such as "en-us").
# Invalid language codes will cause your feed to fail Apple validation.

  author: 'David Fourman, Ben Etherington and Dennis Just'
# The group responsible for creating the show.
# Show author most often refers to the parent company or network of a podcast, but it can also be used to identify the host(s) if none exists.
# Author information is especially useful if a company or organization publishes multiple podcasts. Providing this information will allow listeners to see all shows created
# by the same entity.

  explicit: 'no'
# The podcast parental advisory information.
# The explicit value can be one of the following:
# Yes. If you specify true, indicating the presence of explicit content, Apple Podcasts displays an Explicit parental advisory graphic for your podcast.
# Podcasts containing explicit material aren’t available in some Apple Podcasts territories.
# No. If you specify false, indicating that your podcast doesn’t contain explicit language or adult content, Apple Podcasts displays a Clean parental advisory graphic for your podcast.

  owner:
    my_name: 'Ben Etherington'
    email: 'info@theorbitalmechanics.com'
# The podcast owner contact information.
# Include the email address of the owner in a nested <itunes:email> tag and the name of the owner in a nested <itunes:name> tag.
# Note: The <itunes:owner> tag information is for administrative communication about the podcast and isn’t displayed in Apple Podcasts. Please make sure the email address is
# active and monitored.


  category:
    - ['Science', 'Natural Sciences']
    - ['Science', 'Physics']
    - ['Science', 'Earth Sciences']
# The show category information. For a complete list of categories and subcategories, see Apple Podcasts categories.
# Select the category that best reflects the content of your show. If available, you can also define a subcategory.
# Although you can specify more than one category and subcategory in your RSS feed, Apple Podcasts only recognizes the first category and subcategory.
  
  type: 'episodic'
# The type of show.
# If your show is Serial you must use this tag.
# Its values can be one of the following:
# episodic (default). Specify episodic when episodes are intended to be consumed without any specific order. Apple Podcasts will present newest episodes first and display the
# publish date (required) of each episode. If organized into seasons, the newest season will be presented first - otherwise, episodes will be grouped by year published, newest first.
# For new subscribers, Apple Podcasts adds the newest, most recent episode in their Library.
# serial. Specify serial when episodes are intended to be consumed in sequential order. Apple Podcasts will present the oldest episodes first and display the episode numbers 
# (required) of each episode. If organized into seasons, the newest season will be presented first and <itunes:episode> numbers must be given for each episode.
# For new subscribers, Apple Podcasts adds the first episode to their Library, or the entire current season if using seasons.

  image_show: 'https://images.squarespace-cdn.com/content/5439a3d0e4b0dedc218f23b9/1418314982417-0PNSD5LD6WLV5ZFEWTLM/TOM_2.jpg?format=1500w&amp;content-type=image%2Fjpeg'
# The artwork for the show.
# Specify your show artwork by providing a URL linking to it.
# Depending on their device, subscribers see your podcast artwork in varying sizes. Therefore, make sure your design is effective at both its original size and at thumbnail size.
# You should include a show title, brand, or source name as part of your podcast artwork. Here are additional marketing best practices. For examples of podcast artwork, see the Top
# Podcasts chart. To avoid technical issues when you update your podcast artwork, be sure to:
# Change the artwork file name and URL at the same time
# Verify the web server hosting your artwork allows HTTP head requests
# Artwork must be a minimum size of 1400 x 1400 pixels and a maximum size of 3000 x 3000 pixels, in JPEG or PNG format, 72 dpi, with appropriate file extensions (.jpg, .png), and
# in the RGB colorspace. These requirements are different from the standard RSS image tag specifications.
# Make sure the file type in the URL matches the actual file type of the image file.

  description_show: 'Every week we cover the latest spaceflight news, discuss past, current and future exploration efforts, and take a look at upcoming events. 
  Tune in to hear about how humans get to space, how they stay in space and how unmanned craft reach farther and farther into the universe around us.'
# The show description.
# Where description is text containing one or more sentences describing your podcast to potential listeners. The maximum amount of text allowed for this tag is 4000 characters.
# To include links in your description or rich HTML, adhere to the following technical guidelines: enclose all portions of your XML that contain embedded HTML in a CDATA section
# to prevent formatting issues, and to ensure proper link functionality.